# .travis.yml for prcbench

#branches:
#  only:
#    - master
#    - develop

language: r
r:
  - release
  - devel
cache: packages
sudo: false
warnings_are_errors: true

bioc_required: true
bioc_packages:
 - limma
 - graph
 - RBGL

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
