# .travis.yml for prcbench

#branches:
#  only:
#    - master
#    - develop

language: r
r:
  - release
  - devel
cache: packages
sudo: false
warnings_are_errors: true

bioc_required: true
bioc_packages:
 - limma
 - graph
 - RBGL

r_github_packages:
  - jimhester/covr
after_success:
#  if [ "$TRAVIS_OS_NAME" == "linux" ] &&
#     [ "$TRAVIS_BRANCH" == "master" ] &&
#     ![ "$TRAVIS_R_VERSION" =~ "devel" ]; then
  if ![ "$TRAVIS_R_VERSION" =~ "devel" ]; then
    Rscript -e 'library(covr);codecov()'
  else
    echo "TRAVIS_OS_NAME: $TRAVIS_OS_NAME"
    echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
    echo "TRAVIS_R_VERSION: $TRAVIS_R_VERSION"
  fi

