# .travis.yml for prcbench

os:
 - linux
 - osx

#branches:
#  only:
#    - master
#    - develop

language: r
r:
  - release
  - devel
cache: packages
sudo: false
warnings_are_errors: true

bioc_required: true
bioc_packages:
 - limma
 - graph
 - RBGL

before_install:
  if [ "$TRAVIS_OS_NAME" == "osx" ] &&
     [ "$TRAVIS_R_VERSION" == "devel" ]; then
    Rscript -e 'install.packages("assertthat")';
    Rscript -e 'install.packages("ggplot2")';
    Rscript -e 'install.packages("gridExtra")';
    Rscript -e 'install.packages("precrec")';
    Rscript -e 'install.packages("PRROC")';
    Rscript -e 'install.packages("rJava")';
    Rscript -e 'install.packages("ROCR")';
    Rscript -e 'install.packages("knitr")';
    Rscript -e 'install.packages("rmarkdown")';
    Rscript -e 'install.packages("rex")';
    Rscript -e 'install.packages("crayon")';
  fi

r_github_packages:
  - jimhester/covr

after_success:
  if [ "$TRAVIS_OS_NAME" == "linux" ] &&
     [ "$TRAVIS_R_VERSION" != "devel" ]; then
    Rscript -e 'library(covr);codecov()' >/dev/null;
  else
    echo "TRAVIS_OS_NAME $TRAVIS_OS_NAME";
    echo "TRAVIS_BRANCH $TRAVIS_BRANCH";
    echo "TRAVIS_R_VERSION $TRAVIS_R_VERSION";
  fi
