# .travis.yml for prcbench

#branches:
#  only:
#    - master
#    - develop

#env:
#  global:
#    - CRAN=http://cran.rstudio.com
#    - NOT_CRAN=true
#    - _R_CHECK_CRAN_INCOMING_=false

language: r
r:
  - release
  - devel
cache: packages
sudo: false
warnings_are_errors: true

addons:
  apt:
    packages:
      - r-cran-rjava
bioc_required: true
bioc_packages:
 - limma
 - graph
 - RBGL

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
