# .travis.yml for prcbench

branches:
  only:
    - main
    - develop

os:
 - linux
# - osx

language: r
r:
  - release
  - devel
cache: packages
warnings_are_errors: true
sudo: required

apt_packages:
  - r-cran-rjava

# https://travis-ci.community/t/configuring-a-travis-yml-for-a-package-that-depends-on-rjava/9983
before_install:
  - sudo $(which R) CMD javareconf

matrix:
  exclude:
  - os: osx
    r: devel

bioc_required: true
bioc_packages:
 - limma
 - graph
 - RBGL

r_github_packages:
  - jimhester/covr

after_success:
  if [ "$TRAVIS_OS_NAME" == "linux" ] &&
     [ "$TRAVIS_R_VERSION" != "devel" ]; then
    Rscript -e 'library(covr);codecov()' >/dev/null;
  else
    echo "TRAVIS_OS_NAME $TRAVIS_OS_NAME";
    echo "TRAVIS_BRANCH $TRAVIS_BRANCH";
    echo "TRAVIS_R_VERSION $TRAVIS_R_VERSION";
  fi
