#' Run microbenchmark with a specified set of tools and a sample dataset
#'
#' The \code{run_benchmark} function runs
#'     \code{\link[microbenchmark]{microbenchmark}} for a specified set of tools
#'     and a sample dataset.
#'
#' @param sdat A sample dataset genereated by \code{\link{create_sampleset}} or
#'     \code{\link{create_rnd_sample}}.
#'
#' @param tool_funcs A list of functions generated by
#'     \code{\link{create_toolset}}.
#'
#' @param times The number of iteration used in
#'     \code{\link[microbenchmark]{microbenchmark}}.
#'
#' @param unit A single string to specify the unit used in
#'     \code{\link[microbenchmark]{summary.microbenchmark}}.
#'
#' @return A data frame with microbenchmark results.
#'
#' @seealso \code{\link{create_sampleset}} and \code{\link{create_rnd_sample}}
#'    to generate a sample dataset. \code{\link{create_toolset}} to create a
#'    set of tools. \code{\link[microbenchmark]{microbenchmark}} for
#'    benchmarking details.
#'
#' @examples
#' ## Check Precision-Recall cuvers of a tool set "set1" on a test dataset "r1"
#' res1 <- eval_curves("r1", "set1")
#'
#' @export
eval_curves <- function(testdat_name = "r1", toolset_name = "set1") {
  testdat <- .get_testdat(testdat_name)
  sdata <- prcdata_generator()$new(testdat$scores, testdat$labels)

  toolset <- create_toolset(toolset_name)
  res <- lapply(toolset, function(t) {t(sdata)})

  test_res <- list()
  test_res[["x_range"]] <- do.call(rbind, lapply(res, .eval_x_range))
  test_res[["y_range"]] <- do.call(rbind, lapply(res, .eval_y_range))

  tres <- lapply(res, function(x) {.eval_fpoint(testdat, x)})
  test_res[["fpoint"]] <- do.call(rbind, tres)

  tres <- lapply(res, function(x) {.eval_int_pts(testdat, x)})
  test_res[["int_pts"]] <- do.call(rbind, tres)

  tres <- lapply(res, function(x) {.eval_epoint(testdat, x)})
  test_res[["epoint"]] <- do.call(rbind, tres)

  sfunc <- function(vname) {
    tnames <- rownames(test_res[[vname]])
    rownames(test_res[[vname]]) <- NULL
    df <- as.data.frame(test_res[[vname]])
    df <- cbind(data.frame(test = vname, tool = tnames),
                as.data.frame(test_res[[vname]]))
  }
  do.call(rbind, lapply(names(test_res), sfunc))
}

#
# Get a predefinded test dataset
#
.get_testdat <- function(testdat_name) {
  if (testdat_name == "r1") {
    data(M1DATA)
    M1DATA
  } else if (testdat_name == "r2") {
    data(M2DATA)
    M2DATA
  } else if (testdat_name == "r3") {
    data(M3DATA)
    M3DATA
  } else {
    stop("Ivalid dataset name")
  }
}

#
# Check the x value range of a Precision-Recall curve
#
.eval_x_range <- function(res) {
  score <- 0

  # Test 1
  if (all(res$get_x() >= 0, na.rm = T)) {
    score <- score + 1
  }

  # Test 2
  if (all(res$get_x() <= 1, na.rm = T)) {
    score <- score + 1
  }

  scores <- c(score, 2)
  names(scores) <-  c("success", "total")
  scores
}

#
# Check the y value range of a Precision-Recall curve
#
.eval_y_range <- function(res) {
  score <- 0

  # Test 1
  if (all(res$get_y() >= 0, na.rm = T)) {
    score <- score + 1
  }

  # Test 2
  if (all(res$get_y() <= 1, na.rm = T)) {
    score <- score + 1
  }

  scores <- c(score, 2)
  names(scores) <-  c("success", "total")
  scores
}

#
# Check intermediate points of a Precisoin-Recall curve
#
.eval_int_pts <- function(testdat, res, tolerance = 1e-4) {
  score <- 0

  efunc <- function(i) {
    xidx <- abs(res$get_x() - testdat$bp_x[i]) < tolerance
    ys <- res$get_y()[xidx]

    if (any(abs(ys - testdat$bp_y[i]) < tolerance, na.rm = T)) {
      return(1)
    } else {
      return(0)
    }
  }

  evalsss <- lapply(2:(length(testdat$bp_x) - 1), efunc)
  score <- do.call(sum, evalsss)
  scores <- c(score, length(testdat$bp_x) - 2)
  names(scores) <-  c("success", "total")
  scores
}

#
# Check the first point of a Precisoin-Recall curve
#
.eval_fpoint <- function(testdat, res, tolerance = 1e-4) {
  if (!is.na(res$get_x()[1]) && !is.na(res$get_y()[1])
        && (abs(res$get_x()[1] - testdat$bp_x[1]) < tolerance)
        && (abs(res$get_y()[1] - testdat$bp_y[1]) < tolerance)) {
    score <- 1
  } else {
    score <- 0
  }

  scores <- c(score, 1)
  names(scores) <-  c("success", "total")
  scores
}

#
# Check the end point of a Precisoin-Recall curve
#
.eval_epoint <- function(testdat, res, tolerance = 1e-4) {
  epos1 <- length(res$get_x())
  epos2 <- length(testdat$bp_x)

  if (!is.na(res$get_x()[epos1]) && !is.na(res$get_y()[epos1])
      && (abs(res$get_x()[epos1] - testdat$bp_x[epos2]) < tolerance)
      && (abs(res$get_y()[epos1] - testdat$bp_y[epos2]) < tolerance)) {
    score <- 1
  } else {
    score <- 0
  }

  scores <- c(score, 1)
  names(scores) <-  c("success", "total")
  scores
}
