#' Base class for the wrapper classes of performace evaluatoin tools
#'
#' \code{ToolIFBase} is an abstruct class for the wrapper classes of
#' performace evaluatoin tools. It is an R6 class that contains nine public
#' methods for subclass inheritance.
#'
#' @section Methods:
#' \itemize{
#'  \item \code{call(testdata, retval = TRUE, auc = TRUE)}: It calls an actual
#'      tool to calculate Precision-Recall curves.
#'      \describe{
#'        \item{\code{testdata}}{\code{R6} object generated by the
#'                           \code{prepare_data} function.}
#'        \item{\code{retval}}{A Boolean value to specify whether the method
#'                             returns the AUC score and x-y positions.}
#'        \item{\code{auc}}{A Boolean value to specify  whether the AUC score
#'                         should be calculated.}
#'       }
#'  \item \code{get_toolname()}: Get the name of the tool.
#'  \item \code{get_result()}: Get a list with an AUC score and x-y values.
#'  \item \code{get_x()}: Get a list with Recall values of a Precision-Recall
#'                        curve.
#'  \item \code{get_y()}: Get a list with Precision values of a Precision-Recall
#'                        curve.
#'  \item \code{get_auc()}: Get an AUC score.
#' }
#'
#' @seealso \code{\link{ToolROCR}}, \code{\link{ToolAUCCalculator}},
#'   \code{\link{ToolPerfMeas}}, \code{\link{ToolPRROC}},
#'   and \code{\link{Toolprecrec}} are derived from this class.
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolIFBase <- R6::R6Class(
  "ToolIFBase",
  public = list(
    initialize = function(...) {
      arglist <- list(...)
      if (length(arglist) > 0) {
        stop("Invalid argument")
      }
    },
    call = function(testdata, retval = TRUE, auc = TRUE) {
      result <- private$f_wrapper(testdata, retval, auc)
      if (retval && !is.null(result)) {
        private$set_result(result)
      } else if (auc && !is.null(result$auc)) {
        private$set_auc(result$auc)
      }
      private$called <- TRUE
      self
    },
    get_toolname = function() {private$toolname},
    get_result = function() {private$result},
    get_x = function() {private$result[["x"]]},
    get_y = function() {private$result[["y"]]},
    get_auc = function() {private$result[["auc"]]},
    print = function(...) {
      cat("\n")
      cat("    === Tool interface ===\n")
      cat("\n")

      cat("    Tool name:          ", self$get_toolname(), "\n")
      cat("    Contain predictions:")
      if (private$called) {
        cat(" Yes\n")
      } else {
        cat(" No\n")
      }
      cat("    Availabel methods:   call(testdata, retval, auc)\n")
      cat("                         get_toolname()\n")
      cat("                         get_result()\n")
      cat("                         get_x()\n")
      cat("                         get_y()\n")
      cat("                         get_auc()\n")
      private$print_methods()
      cat("\n")
      invisible(self)
    }
  ),
  private = list(
    toolname = NA,
    called = FALSE,
    print_methods = function() {invisible(NULL)},
    set_result = function(val) {private$result <- val},
    set_auc = function(val) {private$result[["auc"]] <- val},
    result = list(x = NA, y = NA, auc = NA),
    f_wrapper = function(testdata, retval, auc) {NULL}
  )
)

#' ROCR wrapper class
#'
#' \code{ToolROCR} is a wrapper class for
#' \href{https://rocr.bioinf.mpi-sb.mpg.de/}{ROCR}, which is an R library
#' that provides calculatoins of various performance evaluation measures.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' Following six methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testdata, retval = TRUE, auc = TRUE)}
#'   \item \code{get_toolname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}. The object
#' can be also instantiated by \code{\link{create_tools}("ROCR")}.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolroc1 <- ToolROCR$new()
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolROCR <- R6::R6Class(
  "ToolROCR", inherit = ToolIFBase,
  private = list(toolname = "ROCR", f_wrapper = .rocr_wrapper)
)

#' AUCCalculator wrapper class
#'
#' \code{ToolAUCCalculator} is a wrapper class for
#' \href{http://mark.goadrich.com/programs/AUC/}{AUCCalculator}, which is a Java
#' library that provides calculatoins of ROC and Precision-Recall curves.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' \describe{
#'   \item{\code{set_java_call(type, fpath = NULL)}}{
#'     It sets an AUCCalculator jar file.
#'
#'     \describe{
#'       \item{\code{type}}{A string to specify the wrapper method. It must be
#'                          either "syscall" or "rjava". It uses a system call
#'                          and \code{\link[rJava]{.jcall}} of the \code{rJava}
#'                          library, respectively.}
#'       \item{\code{fpath}}{File path of the AUCCalculator jar file,
#'                           e.g. \code{"/path1/path2/auc.jar"}.}
#'     }
#'   }
#' }
#'
#' Following six methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testdata, retval = TRUE, auc = TRUE)}
#'   \item \code{get_toolname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}. The object
#' can be also instantiated by \code{\link{create_tools}("AUCCalculator")}.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolauccalc1 <- ToolAUCCalculator$new()
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolAUCCalculator <- R6::R6Class(
  "ToolAUCCalculator", inherit = ToolIFBase,
  public = list(
    initialize = function(...) {
      arglist <- list(...)
      argnum <- 0
      if (length(arglist) > 0) {
        if ("type" %in% names(arglist)){
          private$type <- arglist[["type"]]
          argnum <- argnum + 1
        }
        if ("fpath" %in% names(arglist)){
          private$fpath <- arglist[["fpath"]]
          argnum <- argnum + 1
        }
        if (length(arglist) != argnum) {
          stop("Invalid argument")
        }
      }
      self$set_java_call()
    },
    set_java_call = function(type = NULL, fpath = NULL) {
      if (is.null(type)) {
        type <- private$type
      }
      if (is.null(fpath)) {
        fpath <- private$fpath
      }
      if (type == "syscall") {
        private$java_call <- .create_syscall_auccalc(fpath)
      } else if (type == "rjava") {
        private$java_call <- .create_rjava_auccalc(fpath)
      }
    }
  ),
  private = list(
    toolname = "AUCCalculator",
    print_methods = function() {
      cat("                         set_java_call(type, fpath)\n")
    },
    type = "syscall",
    fpath = NULL,
    f_wrapper = function(testdata, retval, auc) {
      .auccalc_wrapper(testdata, retval, auc, private$java_call)
    },
    java_call = NULL
  )
)

#' PerfMeas wrapper class
#'
#' \code{ToolPerfMeas} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/PerfMeas/}{PerfMeas},
#' which is an R library that provides several performance measures.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' Following six methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testdata, retval = TRUE, auc = TRUE)}
#'   \item \code{get_toolname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}. The object
#' can be also instantiated by \code{\link{create_tools}("PerfMeas")}.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolpm1 <- ToolPerfMeas$new()
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolPerfMeas <- R6::R6Class(
  "ToolPerfMeas", inherit = ToolIFBase,
  private = list(toolname = "PerfMeas", f_wrapper = .pm_wrapper)
)

#' PRROC wrapper class
#'
#' \code{ToolPRROC} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/PRROC/}{PRROC}, which is an R
#' library that provides calculatoins of ROC and Precision-Recall curves.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' \describe{
#'   \item{\code{set_curve(val)}}{A Boolean value to specifiy whether a
#'                                Precision-Recall curve is calculated.}
#'   \item{\code{set_minStepSize(val)}}{A numeric value to specify the minimum
#'                                      step size between itermediate points.}
#' }
#'
#' Following six methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testdata, retval = TRUE, auc = TRUE)}
#'   \item \code{get_toolname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}. The object
#' can be also instantiated by \code{\link{create_tools}("PRROC")}.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolprroc1 <- ToolPRROC$new()
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolPRROC <- R6::R6Class(
  "ToolPRROC", inherit = ToolIFBase,
  public = list(
    initialize = function(...) {
      arglist <- list(...)
      argnum <- 0
      if (length(arglist) > 0) {
        if ("curve" %in% names(arglist)){
          private$curve <- arglist[["curve"]]
          argnum <- argnum + 1
        }
        if ("minStepSize" %in% names(arglist)){
          private$minStepSize <- arglist[["minStepSize"]]
          argnum <- argnum + 1
        }
        if (length(arglist) != argnum) {
          stop("Invalid argument")
        }
      }
    },
    set_curve = function(val) {private$curve <- val},
    set_minStepSize = function(val) {private$minStepSize <- val}
  ),
  private = list(
    toolname = "PRROC",
    print_methods = function() {
      cat("                         set_curve(val)\n")
      cat("                         set_minStepSize(val)\n")
    },
    f_wrapper = function(testdata, retval, auc) {
      .prroc_wrapper(testdata, retval, auc, private$curve, private$minStepSize)
    },
    curve = TRUE,
    minStepSize = 0.01
  )
)

#' precrec wrapper class
#'
#' \code{Toolprecrec} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/precrec/}{precrec}, which is an
#' R library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as \code{tool_generator("precrec")}.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' Following six methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testdata, retval = TRUE, auc = TRUE)}
#'   \item \code{get_toolname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}. The object
#' can be also instantiated by \code{\link{create_tools}("precrec")}.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolprecrec1 <- Toolprecrec$new()
#'
#' @docType class
#' @format An R6 class object.
#' @export
Toolprecrec <- R6::R6Class(
  "Toolprecrec", inherit = ToolIFBase,
  private = list(toolname = "precrec", f_wrapper = .precrec_wrapper)
)
