#' Base class of performance evaluatoin tools
#'
#' \code{ToolIFBase} is an abstruct class to provide a uniform interface for
#' performace evaluation tools.
#'
#' @section Methods:
#' \itemize{
#'  \item \code{call(testset, calc_auc, store_res)}: It calls an actual
#'      tool to calculate Precision-Recall curves.
#'      \describe{
#'        \item{\code{testset}}{\code{R6} object generated by the
#'                               \code{create_testset} function.}
#'        \item{\code{calc_auc}}{A Boolean value to specify whether the AUC
#'                               score should be calculated.}
#'        \item{\code{store_res}}{A Boolean value to specify whether the
#'                                caluladted curve is retrieved and stored.}
#'       }
#'  \item \code{get_toolname()}: Get the name of the tool.
#'  \item \code{get_setname()}: Get the name of the tool set.
#'  \item \code{get_result()}: Get a list with curve values and the AUC score.
#'  \item \code{get_x()}: Get calculated recall values.
#'  \item \code{get_y()}: Get calculated precision values.
#'  \item \code{get_auc()}: Get tne AUC score.
#' }.
#'
#' @seealso \code{\link{ToolROCR}}, \code{\link{ToolAUCCalculator}},
#'   \code{\link{ToolPerfMeas}}, \code{\link{ToolPRROC}},
#'   and \code{\link{Toolprecrec}} are derived from this class.
#'   \code{\link{create_toolset}} for creating a list of tools.
#'
#' @docType class
#' @format An R6 class object
#' @export
ToolIFBase <- R6::R6Class(
  "ToolIFBase",
  public = list(
    initialize = function(...) {
      private$set_def_params(...)
    },
    call = function(testset, calc_auc, store_res) {
      if (missing(calc_auc)) {
        calc_auc <- private$def_calc_auc
      }
      if (missing(store_res)) {
        store_res <- private$def_store_res
      }
      result <- private$f_wrapper(testset, calc_auc, store_res)
      if (store_res && !is.null(result)) {
        private$set_result(result)
      } else if (calc_auc && !is.null(result$auc)) {
        private$set_auc(result$auc)
      }
      private$called <- TRUE
      self
    },
    get_toolname = function() {private$toolname},
    get_setname = function() {private$setname},
    get_result = function() {private$result},
    get_x = function() {private$result[["x"]]},
    get_y = function() {private$result[["y"]]},
    get_auc = function() {private$result[["auc"]]},
    print = function(...) {
      cat("\n")
      cat("    === Tool interface ===\n")
      cat("\n")

      cat("    Tool name:           ", self$get_toolname(), "\n")
      cat("    Calculate AUC score: ")
      if (private$def_calc_auc) {
        cat(" Yes\n")
      } else {
        cat(" No\n")
      }
      cat("    Store results:       ")
      if (private$def_store_res) {
        cat(" Yes\n")
      } else {
        cat(" No\n")
      }
      cat("    Prediction performed:")
      if (private$called) {
        cat(" Yes\n")
      } else {
        cat(" No\n")
      }
      cat("    Availabel methods:    call(testset, calc_auc, store_res)\n")
      cat("                          get_toolname()\n")
      cat("                          get_setname()\n")
      cat("                          get_result()\n")
      cat("                          get_x()\n")
      cat("                          get_y()\n")
      cat("                          get_auc()\n")
      private$print_methods()
      if (private$helpfile) {
        cat("    Help file:           ",
            paste0("help(\"", class(self)[1], "\")"))
      }
      cat("\n")
      invisible(self)
    }
  ),
  private = list(
    set_def_params = function(...) {
      arglist <- list(...)
      if (length(arglist) > 0) {
        if ("setname" %in% names(arglist)){
          private$setname <- arglist[["setname"]]
        }
        if ("calc_auc" %in% names(arglist)){
          private$def_calc_auc <- arglist[["calc_auc"]]
        }
        if ("store_res" %in% names(arglist)){
          private$def_store_res <- arglist[["store_res"]]
        }
      }
    },
    toolname = NA,
    setname = NA,
    called = FALSE,
    def_calc_auc = TRUE,
    def_store_res = TRUE,
    print_methods = function() {invisible(NULL)},
    set_result = function(val) {private$result <- val},
    set_auc = function(val) {private$result[["auc"]] <- val},
    result = list(x = NA, y = NA, auc = NA),
    f_wrapper = function(testset, calc_auc, store_res) {NULL},
    helpfile = TRUE
  )
)

#' R6 class of the ROCR tool
#'
#' \code{ToolROCR} is a wrapper class for
#' the \href{https://rocr.bioinf.mpi-sb.mpg.de/}{ROCR} tool, which is an R
#' library that provides calculatoins of various performance evaluation
#' measures.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' Following seven methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testset, calc_auc, store_res)}
#'   \item \code{get_toolname()}
#'   \item \code{get_setname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}.
#'    \code{\link{create_toolset}} for creating a list of tools.
#'
#' @examples
#' ## Initialization
#' toolrocr <- ToolROCR$new()
#'
#' ## Show object info
#' toolrocr
#'
#' ## create_toolset should be used for benchmarking and curve evalation
#' toolrocr2 <- create_toolset("ROCR")
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolROCR <- R6::R6Class(
  "ToolROCR", inherit = ToolIFBase,
  private = list(toolname = "ROCR", f_wrapper = .rocr_wrapper)
)

#' R6 class of the AUCCalculator tool
#'
#' \code{ToolAUCCalculator} is a wrapper class for
#' the \href{http://mark.goadrich.com/programs/AUC/}{AUCCalculator} tool, which
#' is a Java library that provides calculatoins of ROC and Precision-Recall
#' curves.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#'
#' \describe{
#'   \item{\code{set_java_call(type, fpath = NULL)}}{
#'     It sets an AUCCalculator jar file.
#'
#'     \describe{
#'       \item{\code{type}}{A string to specify the wrapper method. It must be
#'                          either "syscall" or "rjava". It uses a system call
#'                          and \code{\link[rJava]{.jcall}} of the \code{rJava}
#'                          library, respectively.}
#'       \item{\code{fpath}}{File path of the AUCCalculator jar file,
#'                           e.g. \code{"/path1/path2/auc.jar"}.}
#'     }
#'   }
#' }
#'
#' Following seven methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call((testset, calc_auc, store_res)}
#'   \item \code{get_toolname()}
#'   \item \code{get_setname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}.
#'    \code{\link{create_toolset}} for creating a list of tools.
#'
#' @examples
#' ## Initialization
#' toolauccalc <- ToolAUCCalculator$new()
#'
#' ## Show object info
#' toolauccalc
#'
#' ## create_toolset should be used for benchmarking and curve evalation
#' toolauccalc2 <- create_toolset("AUCCalculator")
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolAUCCalculator <- R6::R6Class(
  "ToolAUCCalculator", inherit = ToolIFBase,
  public = list(
    initialize = function(...) {
      private$set_def_params(...)

      arglist <- list(...)
      if (length(arglist) > 0) {
        if ("type" %in% names(arglist)){
          private$type <- arglist[["type"]]
        }
        if ("fpath" %in% names(arglist)){
          private$fpath <- arglist[["fpath"]]
        }
      }
    },
    set_java_call = function(type = NULL, fpath = NULL) {
      if (!is.null(type)) {
        private$type <- type
      }
      if (!is.null(fpath)) {
        private$fpath <- fpath
      }
    }
  ),
  private = list(
    toolname = "AUCCalculator",
    print_methods = function() {
      cat("                          set_java_call(type, fpath)\n")
    },
    type = "syscall",
    fpath = NA,
    f_wrapper = function(testset, calc_auc, store_res) {
      if (private$type == "syscall") {
        java_call <- .create_syscall_auccalc(private$fpath)
      } else if (type == "rjava") {
        java_call <- .create_rjava_auccalc(private$fpath)
      }
      .auccalc_wrapper(testset, calc_auc, store_res, java_call)
    }
  )
)

#' R6 class of the PerfMeas tool
#'
#' \code{ToolPerfMeas} is a wrapper class for
#' the \href{https://cran.r-project.org/web/packages/PerfMeas/}{PerfMeas} tool,
#' which is an R library that provides several performance measures.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' Following seven methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testset, calc_auc, store_res)}
#'   \item \code{get_toolname()}
#'   \item \code{get_setname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}.
#'    \code{\link{create_toolset}} for creating a list of tools.
#'
#' @examples
#' ## Initialization
#' toolperf <- ToolPerfMeas$new()
#'
#' ## Show object info
#' toolperf
#'
#' ## create_toolset should be used for benchmarking and curve evalation
#' toolperf2 <- create_toolset("PerfMeas")
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolPerfMeas <- R6::R6Class(
  "ToolPerfMeas", inherit = ToolIFBase,
  private = list(toolname = "PerfMeas", f_wrapper = .pm_wrapper)
)

#' R6 class of the PRROC tool
#'
#' \code{ToolPRROC} is a wrapper class for
#' the \href{https://cran.r-project.org/web/packages/PRROC/}{PRROC} tool, which
#' is an R library that provides calculatoins of ROC and Precision-Recall
#' curves.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' \describe{
#'   \item{\code{set_curve(val)}}{A Boolean value to specifiy whether a
#'                                Precision-Recall curve is calculated.}
#'   \item{\code{set_minStepSize(val)}}{A numeric value to specify the minimum
#'                                      step size between two itermediate
#'                                      points.}
#' }
#'
#' Following seven methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testset, calc_auc, store_res)}
#'   \item \code{get_toolname()}
#'   \item \code{get_setname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}.
#'    \code{\link{create_toolset}} for creating a list of tools.
#'
#' @examples
#' ## Initialization
#' toolprroc <- ToolPRROC$new()
#'
#' ## Show object info
#' toolprroc
#'
#' ## create_toolset should be used for benchmarking and curve evalation
#' toolprroc2 <- create_toolset("PRROC")
#'
#' @docType class
#' @format An R6 class object.
#' @export
ToolPRROC <- R6::R6Class(
  "ToolPRROC", inherit = ToolIFBase,
  public = list(
    initialize = function(...) {
      private$set_def_params(...)

      arglist <- list(...)
      if (length(arglist) > 0) {
        if ("curve" %in% names(arglist)){
          private$curve <- arglist[["curve"]]
        }
        if ("minStepSize" %in% names(arglist)){
          private$minStepSize <- arglist[["minStepSize"]]
        }
      }
    },
    set_curve = function(val) {private$curve <- val},
    set_minStepSize = function(val) {private$minStepSize <- val}
  ),
  private = list(
    toolname = "PRROC",
    print_methods = function() {
      cat("                          set_curve(val)\n")
      cat("                          set_minStepSize(val)\n")
    },
    f_wrapper = function(testset, calc_auc, store_res) {
      .prroc_wrapper(testset, calc_auc, store_res, private$curve,
                     private$minStepSize)
    },
    curve = TRUE,
    minStepSize = 0.01
  )
)

#' R6 class of the precrec tool
#'
#' \code{Toolprecrec} is a wrapper class for
#' the \href{https://cran.r-project.org/web/packages/precrec/}{precrec} tool,
#' which is an R library that provides calculatoins of ROC and Precision-Recall
#' curves.
#'
#' @section Inheritance:
#' \code{\link{ToolIFBase}}
#'
#' @section Methods:
#' Following seven methods are interited from \code{\link{ToolIFBase}}. See
#' \code{\link{ToolIFBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(testset, calc_auc, store_res)}
#'   \item \code{get_toolname()}
#'   \item \code{get_setname()}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolIFBase}}.
#'    \code{\link{create_toolset}} for creating a list of tools.
#'
#' @examples
#' ## Initialization
#' toolprecrec <- Toolprecrec$new()
#'
#' ## Show object info
#' toolprecrec
#'
#' ## create_toolset should be used for benchmarking and curve evalation
#' toolprecrec2 <- create_toolset("precrec")
#'
#' @docType class
#' @format An R6 class object.
#' @export
Toolprecrec <- R6::R6Class(
  "Toolprecrec", inherit = ToolIFBase,
  private = list(toolname = "precrec", f_wrapper = .precrec_wrapper)
)
