#' Base class for the wrapper classes of performace evaluatoin tools
#'
#' ToolBase is an abstruct class for the wrapper classes of performace
#' evaluatoin tools. It is an R6 class that contains nine public methods
#' for subclass inheritance.
#'
#' @docType class
#' @keywords data
#'
#' @usage It must be subclassed.
#'
#' @format \code{R6} (abstruct class)
#'
#' @section Methods:
#' \describe{
#'   \item{\code{call(sdat, retval = TRUE, auc = TRUE)}}{
#'     It calls an actuall tool to calculate Precision-Recall curves.
#'
#'     \describe{
#'       \item{\code{sdat}}{\code{R6} object generated by the
#'                          \code{prepare_data} function.}
#'       \item{\code{retval}}{A Boolean value to specify whether the method
#'                            returns the AUC score and x-y positions.}
#'       \item{\code{auc}}{A Boolean value to specify  whether the AUC score
#'                         should be calculated.}
#'      }
#'    }
#'
#'   \item{\code{get_result()}}{
#'     Get a list with an AUC score and x-y values.
#'   }
#'
#'   \item{\code{get_x()}}{
#'     Get a list with Recall values of a Precision-Recall curve.
#'   }
#'
#'   \item{\code{get_y()}}{
#'     Get a list with Precision values of a Precision-Recall curve.
#'   }
#'
#'   \item{\code{get_auc()}}{
#'      Get an AUC score
#'   }
#' }
#'
#' @seealso \code{\link{ToolROCR}}, \code{\link{ToolAUCCalculator}},
#'   \code{\link{ToolPerfMeas}}, \code{\link{ToolPRROC}},
#'   and \code{\link{Toolprecrec}} are derived from this class.
#'   \code{\link{tool_generator}} is a generator function that uses this class.
#'
#' @export
ToolBase <- .tool_base_generator()

#' ROCR wrapper class
#'
#' \code{ToolROCR} is a wrapper class for
#' \href{https://rocr.bioinf.mpi-sb.mpg.de/}{ROCR}, which is an R library
#' that provides calculatoins of various performance evaluation measures. It
#' is generated by a generator function as \code{tool_generator("ROCR")}.
#'
#' @docType class
#' @keywords data
#'
#' @usage ToolROCR$new()
#'
#' @format \code{R6}
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolBase}}.
#' \code{\link{tool_generator}} is a generator function for this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolroc1 <- ToolROCR$new()
#'
#' ## tool_generator can also be used to create a wrapper object
#' toolroc2 <- tool_generator("ROCR")$new()
#'
#' @export
ToolROCR <- tool_generator("ROCR")

#' AUCCalculator wrapper class
#'
#' \code{ToolAUCCalculator} is a wrapper class for
#' \href{http://mark.goadrich.com/programs/AUC/}{AUCCalculator}, which is a Java
#' library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as
#' \code{tool_generator("AUCCalculator")}.
#'
#' @docType class
#' @keywords data
#'
#' @usage ToolAUCCalculator$new()
#'
#' @format \code{R6}
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#'
#' \describe{
#'   \item{\code{set_java_call(type, fpath = NULL)}}{
#'     It sets an AUCCalculator jar file.
#'
#'     \describe{
#'       \item{\code{type}}{A string to specify the wrapper method. It must be
#'                          either "syscall" or "rjava". It uses a system call
#'                          and \code{\link[rJava]{.jcall}} of the \code{rJava}
#'                          library, respectively.}
#'       \item{\code{fpath}}{File path of the AUCCalculator jar file,
#'                           e.g. \code{"/path1/path2/auc.jar"}.}
#'     }
#'   }
#' }
#'
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolauccalc1 <- ToolAUCCalculator$new()
#'
#' ## tool_generator can also be used to create a wrapper object
#' toolauccalc2 <- tool_generator("AUCCalculator")$new()
#'
#' @export
ToolAUCCalculator <- tool_generator("AUCCalculator")

#' PerfMeas wrapper class
#'
#' \code{ToolPerfMeas} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/PerfMeas/}{PerfMeas},
#' which is an R library that provides several performance measures. It is
#' generated by a generator function as \code{tool_generator("PerfMeas")}.
#'
#' @docType class
#' @keywords data
#'
#' @usage ToolPerfMeas$new()
#'
#' @format \code{R6}
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolpm1 <- ToolPerfMeas$new()
#'
#' ## tool_generator can also be used to create a wrapper object
#' toolpm2 <- tool_generator("PerfMeas")$new()
#'
#' @export
ToolPerfMeas <- tool_generator("PerfMeas")

#' PRROC wrapper class
#'
#' \code{ToolPRROC} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/PRROC/}{PRROC}, which is an R
#' library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as
#' \code{tool_generator("PRROC")}.
#'
#' @docType class
#' @keywords data
#'
#' @usage ToolPRROC$new()
#'
#' @format \code{R6}
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#'
#' \describe{
#'   \item{\code{set_curve(val)}}{A Boolean value to specifiy whether a
#'                                Precision-Recall curve is calculated.}
#'   \item{\code{set_minStepSize(val)}}{A numeric value to specify the minimum
#'                                      step size between itermediate points.}
#' }
#'
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolprroc1 <- ToolPRROC$new()
#'
#' ## tool_generator can also be used to create a wrapper object
#' toolprroc2 <- tool_generator("PRROC")$new()
#'
#' @export
ToolPRROC <- tool_generator("PRROC")

#' precrec wrapper class
#'
#' \code{Toolprecrec} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/precrec/}{precrec}, which is an
#' R library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as \code{tool_generator("precrec")}.
#'
#' @docType class
#' @keywords data
#'
#' @usage Toolprecrec$new()
#'
#' @format \code{R6}
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolprecrec1 <- Toolprecrec$new()
#'
#' ## tool_generator can also be used to create a wrapper object
#' toolprecrec2 <- tool_generator("precrec")$new()
#'
#' @export
Toolprecrec <- tool_generator("precrec")
