#' Input dataset class for performance evaluation tools
#'
#' \code{PRCData} is a class that contans scores and labels as input data for
#'   performance evaluation tools.
#'
#' @docType class
#' @keywords data
#'
#' @usage PRCData$new(scores = NULL, labels = NULL, datname = NA) \describe{ \item{\code{scores}}{A numeric vector of predicted scores.} \item{\code{labels}}{A numeric vector of labels.} \item{\code{datname}}{A string for a name of the data set.}}
#'
#' @format \code{R6}
#'
#' @section Methods:
#' \describe{
#'
#'   \item{\code{get_datname()}}{
#'     Get a string of the dataset name.
#'   }
#'
#'   \item{\code{get_scores()}}{
#'     Get a vector of predicted scores.
#'   }
#'
#'   \item{\code{get_labels()}}{
#'     Get a vector of observed labels.
#'   }
#'
#'   \item{\code{get_fg()}}{
#'      Get a vector of positive scores.
#'   }
#'
#'   \item{\code{get_bg()}}{
#'      Get a vector of negative scores.
#'   }
#'
#'   \item{\code{get_fname()}}{
#'      Get a file name that contains scores and labels.
#'   }
#'
#'   \item{\code{del_file()}}{
#'      Get a file name that contains scores and labels.
#'   }
#'
#' }
#'
#' @seealso \code{\link{prcdata_generator}} is a generator function that creates
#'  this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any methods
#' prcdata <- PRCData$new(c(0.1, 0.2, 0.3), c(0, 1, 1), "m1")
#'
#' @export
PRCData <- prcdata_generator()

#' Base class for the wrapper classes of performace evaluatoin tools
#'
#' \code{ToolBase} is an abstruct class for the wrapper classes of performace
#' evaluatoin tools. It is an R6 class that contains nine public methods
#' for subclass inheritance.
#'
#' @section Methods:
#' \itemize{
#'  \item \code{call(sdat, retval = TRUE, auc = TRUE)}: It calls an actuall tool
#'      to calculate Precision-Recall curves.
#'      \describe{
#'        \item{\code{sdat}}{\code{R6} object generated by the
#'                           \code{prepare_data} function.}
#'        \item{\code{retval}}{A Boolean value to specify whether the method
#'                             returns the AUC score and x-y positions.}
#'        \item{\code{auc}}{A Boolean value to specify  whether the AUC score
#'                         should be calculated.}
#'       }
#'  \item \code{get_result()}: Get a list with an AUC score and x-y values.
#'  \item \code{get_x()}: Get a list with Recall values of a Precision-Recall
#'                        curve.
#'  \item \code{get_y()}: Get a list with Precision values of a Precision-Recall
#'                        curve.
#'  \item \code{get_auc()}: Get an AUC score.
#' }
#'
#' @seealso \code{\link{ToolROCR}}, \code{\link{ToolAUCCalculator}},
#'   \code{\link{ToolPerfMeas}}, \code{\link{ToolPRROC}},
#'   and \code{\link{Toolprecrec}} are derived from this class.
#'   \code{\link{create_tool}} is a generator function that uses this class.
#'
#' @docType class
#' @keywords internal
#' @format An R6 class object.
#' @export
ToolBase <- R6::R6Class(
  "ToolBase",
  public = list(
    initialize = function(...) {
      arglist <- list(...)
      if (length(arglist) > 0) {
        stop("Invalid argument")
      }
    },
    call = function(sdat, retval = TRUE, auc = TRUE) {
      result <- private$f_wrapper(sdat, retval, auc)
      if (retval && !is.null(result)) {
        private$set_result(result)
      } else if (auc && !is.null(result$auc)) {
        private$set_auc(result$auc)
      }
      self
    },
    get_result = function() {private$result},
    get_x = function() {private$result[["x"]]},
    get_y = function() {private$result[["y"]]},
    get_auc = function() {private$result[["auc"]]}
  ),
  private = list(
    set_result = function(val) {private$result <- val},
    set_auc = function(val) {private$result[["auc"]] <- val},
    result = list(x = NA, y = NA, auc = NA),
    f_wrapper = function(sdat, retval, auc) {NULL}
  )
)

#' ROCR wrapper class
#'
#' \code{ToolROCR} is a wrapper class for
#' \href{https://rocr.bioinf.mpi-sb.mpg.de/}{ROCR}, which is an R library
#' that provides calculatoins of various performance evaluation measures. It
#' is generated by a generator function as \code{tool_generator("ROCR")}.
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolBase}}.
#' \code{\link{create_tool}} is a generator function for this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolroc1 <- ToolROCR$new()
#'
#' @docType class
#' @keywords internal
#' @format An R6 class object.
#' @export
ToolROCR <- R6::R6Class(
  "ToolROCR", inherit = ToolBase,
  private = list(f_wrapper = .rocr_wrapper)
)

#' AUCCalculator wrapper class
#'
#' \code{ToolAUCCalculator} is a wrapper class for
#' \href{http://mark.goadrich.com/programs/AUC/}{AUCCalculator}, which is a Java
#' library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as
#' \code{tool_generator("AUCCalculator")}.
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' \describe{
#'   \item{\code{set_java_call(type, fpath = NULL)}}{
#'     It sets an AUCCalculator jar file.
#'
#'     \describe{
#'       \item{\code{type}}{A string to specify the wrapper method. It must be
#'                          either "syscall" or "rjava". It uses a system call
#'                          and \code{\link[rJava]{.jcall}} of the \code{rJava}
#'                          library, respectively.}
#'       \item{\code{fpath}}{File path of the AUCCalculator jar file,
#'                           e.g. \code{"/path1/path2/auc.jar"}.}
#'     }
#'   }
#' }
#'
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolBase}}.
#' \code{\link{create_tool}} is a generator function for this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolauccalc1 <- ToolAUCCalculator$new()
#'
#' @docType class
#' @keywords internal
#' @format An R6 class object.
#' @export
ToolAUCCalculator <- R6::R6Class(
  "ToolAUCCalculator", inherit = ToolBase,
  public = list(
    initialize = function(...) {
      arglist <- list(...)
      argnum <- 0
      if (length(arglist) > 0) {
        if ("type" %in% names(arglist)){
          private$type <- arglist[["type"]]
          argnum <- argnum + 1
        }
        if ("fpath" %in% names(arglist)){
          private$fpath <- arglist[["fpath"]]
          argnum <- argnum + 1
        }
        if (length(arglist) != argnum) {
          stop("Invalid argument")
        }
      }
      self$set_java_call()
    },
    set_java_call = function(type = NULL, fpath = NULL) {
      if (is.null(type)) {
        type <- private$type
      }
      if (is.null(fpath)) {
        fpath <- private$fpath
      }
      if (type == "syscall") {
        private$java_call <- .create_syscall_auccalc(fpath)
      } else if (type == "rjava") {
        private$java_call <- .create_rjava_auccalc(fpath)
      }
    }
  ),
  private = list(
    type = "syscall",
    fpath = NULL,
    f_wrapper = function(sdat, retval, auc) {
      .auccalc_wrapper(sdat, retval, auc, private$java_call)
    },
    java_call = NULL
  )
)

#' PerfMeas wrapper class
#'
#' \code{ToolPerfMeas} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/PerfMeas/}{PerfMeas},
#' which is an R library that provides several performance measures. It is
#' generated by a generator function as \code{tool_generator("PerfMeas")}.
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolBase}}.
#' \code{\link{create_tool}} is a generator function for this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolpm1 <- ToolPerfMeas$new()
#'
#' @docType class
#' @keywords internal
#' @format An R6 class object.
#' @export
ToolPerfMeas <- R6::R6Class(
  "ToolPerfMeas", inherit = ToolBase,
  private = list(f_wrapper = .pm_wrapper)
)

#' PRROC wrapper class
#'
#' \code{ToolPRROC} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/PRROC/}{PRROC}, which is an R
#' library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as
#' \code{tool_generator("PRROC")}.
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' \describe{
#'   \item{\code{set_curve(val)}}{A Boolean value to specifiy whether a
#'                                Precision-Recall curve is calculated.}
#'   \item{\code{set_minStepSize(val)}}{A numeric value to specify the minimum
#'                                      step size between itermediate points.}
#' }
#'
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolBase}}.
#' \code{\link{create_tool}} is a generator function for this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolprroc1 <- ToolPRROC$new()
#'
#' @docType class
#' @keywords internal
#' @format An R6 class object.
#' @export
ToolPRROC <- R6::R6Class(
  "ToolPRROC", inherit = ToolBase,
  public = list(
    initialize = function(...) {
      arglist <- list(...)
      argnum <- 0
      if (length(arglist) > 0) {
        if ("curve" %in% names(arglist)){
          private$curve <- arglist[["curve"]]
          argnum <- argnum + 1
        }
        if ("minStepSize" %in% names(arglist)){
          private$minStepSize <- arglist[["minStepSize"]]
          argnum <- argnum + 1
        }
        if (length(arglist) != argnum) {
          stop("Invalid argument")
        }
      }
    },
    set_curve = function(val) {private$curve <- val},
    set_minStepSize = function(val) {private$minStepSize <- val}
  ),
  private = list(
    f_wrapper = function(sdat, retval, auc) {
      .prroc_wrapper(sdat, retval, auc, private$curve, private$minStepSize)
    },
    curve = TRUE,
    minStepSize = 0.01
  )
)

#' precrec wrapper class
#'
#' \code{Toolprecrec} is a wrapper class for
#' \href{https://cran.r-project.org/web/packages/precrec/}{precrec}, which is an
#' R library that provides calculatoins of ROC and Precision-Recall curves. It
#' is generated by a generator function as \code{tool_generator("precrec")}.
#'
#' @section Inheritance:
#' \code{\link{ToolBase}}
#'
#' @section Methods:
#' Following five methods are interited from \code{\link{ToolBase}}. See
#' \code{\link{ToolBase}} for the method descriptions.
#' \itemize{
#'   \item \code{call(sdat, retval = TRUE, auc = TRUE)}
#'   \item \code{get_result()}
#'   \item \code{get_x()}
#'   \item \code{get_y()}
#'   \item \code{get_auc()}
#' }
#'
#' @seealso This class is derived from \code{\link{ToolBase}}.
#' \code{\link{create_tool}} is a generator function for this class.
#'
#' @examples
#' ## An object needs to be instantiated from the class
#' ## before calling any wrapper functions
#' toolprecrec1 <- Toolprecrec$new()
#'
#' @docType class
#' @keywords internal
#' @format An R6 class object.
#' @export
Toolprecrec <- R6::R6Class(
  "Toolprecrec", inherit = ToolBase,
  private = list(f_wrapper = .precrec_wrapper)
)
